// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx2qEqNGh-OeffM8E4lZ_EMAEmcUXtNJ0',
    appId: '1:1016560352584:web:671cbf5e2d95280ea5077d',
    messagingSenderId: '1016560352584',
    projectId: 'laby-7f7ee',
    authDomain: 'laby-7f7ee.firebaseapp.com',
    storageBucket: 'laby-7f7ee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQoZC0YanHdSWt1pZcQlDVaEEkN29CJSk',
    appId: '1:1016560352584:android:c95b0f7f7e509e95a5077d',
    messagingSenderId: '1016560352584',
    projectId: 'laby-7f7ee',
    storageBucket: 'laby-7f7ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9sAVm8pJBksRhO752rYpCtVRGCJ3zS5c',
    appId: '1:1016560352584:ios:e3e9ddb8034cb19fa5077d',
    messagingSenderId: '1016560352584',
    projectId: 'laby-7f7ee',
    storageBucket: 'laby-7f7ee.firebasestorage.app',
    iosBundleId: 'com.example.logitrackApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9sAVm8pJBksRhO752rYpCtVRGCJ3zS5c',
    appId: '1:1016560352584:ios:e3e9ddb8034cb19fa5077d',
    messagingSenderId: '1016560352584',
    projectId: 'laby-7f7ee',
    storageBucket: 'laby-7f7ee.firebasestorage.app',
    iosBundleId: 'com.example.logitrackApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx2qEqNGh-OeffM8E4lZ_EMAEmcUXtNJ0',
    appId: '1:1016560352584:web:81b39d538afe160ca5077d',
    messagingSenderId: '1016560352584',
    projectId: 'laby-7f7ee',
    authDomain: 'laby-7f7ee.firebaseapp.com',
    storageBucket: 'laby-7f7ee.firebasestorage.app',
  );

}
